### ISSUE TITLE
Simpler Condition Hierarchy

### ISSUE THREAD

**Issue by serpi90** [iot-uca/IoT#32]
Unify `=`,`~=`,`<`,`<=`,`>`,`>=` conditions into a simple class, suggestions: `ArithmeticCondition` or `ComparisonCondition`.

**Comment by fortizpenaloza** [comment]
I agree. ArithmeticCondition is a better name

**Comment by serpi90** [comment]
Done in 64e4f34cd5f39fe701787a265d5af7d1eee87da5
